### ISSUE TITLE
Fix CI failures

### ISSUE THREAD

**Issue by ocefpaf** [ioos/notebooks_demos#216]
- [X] figure out missing data in `2016-12-19-exploring_csw.ipynb` (#214)
- [X] update code to latest `folium` to fix ``folium.element` call (#215, #217, and #219)
- [X] Fix python 3 syntax (#211)
- [X] use iris with `matplotlib 2` (https://github.com/conda-forge/iris-feedstock/pull/22) and the 1-dim label patch (https://github.com/SciTools/iris/pull/2360) to fix `TypeError: sequence item 0: expected str instance, numpy.bytes_ found` (#217)
